packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/models'
  - 'packages/server'
  - 'packages/tmt'
  # - 'components/**'
  # # exclude packages that are inside test directories
  # - '!**/test/**'
