export const enum Dashboards {
  HOME = 'HOME',
  TRIAL = 'TRIAL',
  TRIAL_INFO = 'TRIAL_INFO',
  USERS = 'USERS',
  STAKEHOLDERS = 'STAKEHOLDERS',
  OBJECTIVES = 'OBJECTIVES',
  EXECUTE = 'EXECUTE',
}
