import { MessageType, uniqueId } from 'trial-manager-models';

export const selectedMessageTypes = [
  // {
  //   id: uniqueId(),
  //   name: 'Change observer questionnaire',
  //   messageForm: 'system_request_change_of_trial_stage',
  //   messageType: MessageType.CHANGE_OBSERVER_QUESTIONNAIRES,
  //   kafkaTopic: 'system_request_change_of_trial_stage',
  //   useNamespace: false,
  //   iconName: 'alt_route',
  //   useCustomGUI: false,
  // },
  {
    id: uniqueId(),
    name: 'Change exercise phase',
    messageForm: 'system_tm_phase_message',
    messageType: MessageType.PHASE_MESSAGE,
    kafkaTopic: 'system_tm_phase_message',
    useNamespace: false,
    iconName: 'alt_route',
    useCustomGUI: false,
  },
  {
    id: uniqueId(),
    name: 'Send CAP message',
    messageForm: 'standard_cap',
    messageType: MessageType.CAP_MESSAGE,
    kafkaTopic: 'standard_cap',
    useNamespace: false,
    iconName: 'crisis_alert',
    useCustomGUI: false,
  },
  {
    id: uniqueId(),
    name: 'Send email, reports, or other posts',
    messageForm: 'simulation_entity_post',
    messageType: MessageType.POST_MESSAGE,
    kafkaTopic: 'simulation_entity_post',
    useNamespace: false,
    iconName: 'mail',
    useCustomGUI: false,
  },
  {
    id: uniqueId(),
    name: 'Send file',
    messageForm: 'send_file',
    messageType: MessageType.SEND_FILE,
    kafkaTopic: 'send_file',
    useNamespace: false,
    iconName: 'attach_file',
    useCustomGUI: false,
  },
  {
    id: uniqueId(),
    name: 'Send message (JSON)',
    messageForm: 'send_message',
    messageType: MessageType.SEND_MESSAGE,
    kafkaTopic: 'send_message',
    useNamespace: false,
    iconName: 'code',
    useCustomGUI: false,
  },
  {
    id: uniqueId(),
    name: 'Send inject',
    messageForm: 'simulation_request_startinject',
    messageType: MessageType.START_INJECT,
    kafkaTopic: 'simulation_request_startinject',
    useNamespace: false,
    iconName: 'bolt',
    useCustomGUI: false,
  },
  {
    id: 'rp_msg',
    name: 'Role Player Message',
    messageForm: 'ROLE_PLAYER_MESSAGE',
    messageType: MessageType.ROLE_PLAYER_MESSAGE,
    kafkaTopic: 'system_tm_role_player',
    useNamespace: false,
    iconName: 'person',
    useCustomGUI: false,
  },
];
