export enum ActorType {
  BUILDER = 'BUILDER',
  INSTRUCTOR = 'INSTRUCTOR',
  OBSERVER = 'OBSERVER',
  ROLE_PLAYER = 'ROLE_PLAYER',
  PARTICIPANT = 'PARTICIPANT',
  OTHER = 'OTHER',
  SIMULATOR = 'SIMULATOR',
  UNKNOWN = 'UNKNOWN',
}
