export enum MessageType {
  CHECKPOINT = 'CHECKPOINT',
  ROLE_PLAYER_MESSAGE = 'ROLE_PLAYER_MESSAGE',
  PHASE_MESSAGE = 'PHASE_MESSAGE',
  POST_MESSAGE = 'POST_MESSAGE',
  GEOJSON_MESSAGE = 'GEOJSON_MESSAGE',
  CHANGE_OBSERVER_QUESTIONNAIRES = 'CHANGE_OBSERVER_QUESTIONNAIRES',
  CAP_MESSAGE = 'CAP_MESSAGE',
  LCMS_MESSAGE = 'LCMS_MESSAGE',
  START_INJECT = 'START_INJECT',
  REQUEST_UNIT_TRANSPORT = 'REQUEST_UNIT_TRANSPORT',
  SET_AFFECTED_AREA = 'SET_AFFECTED_AREA',
  SUMO_CONFIGURATION = 'SUMO_CONFIGURATION',
}
