export enum MessageType {
  ROLE_PLAYER_MESSAGE,
  PHASE_MESSAGE,
  POST_MESSAGE,
  GEOJSON_MESSAGE,
  AUTOMATED_ACTION,
  CHANGE_OBSERVER_QUESTIONNAIRES,
  CAP_MESSAGE,
  LCMS_MESSAGE,
  START_INJECT,
  REQUEST_UNIT_TRANSPORT,
  SET_AFFECTED_AREA,
  SUMO_CONFIGURATION,
}
