export enum InjectType {
  PARTICIPANT_MESSAGE = 'PARTICIPANT_MESSAGE',
  OBSERVER_MESSAGE = 'OBSERVER_MESSAGE',
  ROLE_PLAYER_MESSAGE = 'ROLE_PLAYER_MESSAGE',
  OPERATOR_MESSAGE = 'OPERATOR_MESSAGE',
  AUTOMATED_ACTION = 'AUTOMATED_ACTION',
  BRANCH = 'BRANCH',
  WAIT_FOR_OPERATOR_INPUT = 'WAIT_FOR_OPERATOR_INPUT',
}
